### PR TITLE
Add forEmber section in readme

### PR DESCRIPTION
**Pull request by josemarluedke**
This complements #21.

### CODE REVIEW

**Comment by rwjblue** [comment]
You rock, thank you!

**Comment by ivanvanderbyl** [comment]
Hey @rwjblue, reckon you could cut another release of this to include this change? I'd like to patch https://github.com/jmurphyau/ember-get-helper to detect ember-source.

**Comment by rwjblue** [comment]
@ivanvanderbyl - This change is only a README tweak.  1.2.0 includes the `.forEmber` method already...

**Comment by ivanvanderbyl** [comment]
ah no kidding, I completely missed that when scanning through the source.

**Pull request merged**
