### PR TITLE
update to latest semver package

### PR DESCRIPTION
**Pull request by jakesjews**

### CODE REVIEW

**Comment by pswai** [comment]
Are we merging this anytime soon?

**Comment by rwjblue** [comment]
I don't have any issues with updating, but I need to research what breaking changes were included from 4.x to 5.x. That's the main blocker here...

**Comment by jakesjews** [comment]
@rwjblue it looks like  the breaking change was that [the semver package only supports commonjs now](https://github.com/npm/node-semver/commit/41b56fa573d1ef0d1718777a8a21ae1b57ebcd83) but since were using it in that way it should be ok.

**Comment by pswai** [comment]
@rwjblue yea that seems to be the only commit between 4.3.6 and 5.0.0, so it should be fine

**Pull request merged**
